name: Sincronizacion Bidireccional Automatizada

on:
    push:
        branches:
            [ "Feature", "HotFix", "Feature/*", "HotFix/*" ]

jobs:
    sync-branches:
        runs-on: ubuntu-latest
        steps:
            #1. Clonacion del repositorio con historial de ramas
            - name: Descarga del codigo del repositorio
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            #2. Configuracion de identidad Git en el contenedor
            - name: Configuracion de identidad Git
              run: |
                git config --global user.name "Github Actions"
                git config --global user.email "actions@github.com"

                git fetch --all

            #3. Detectar la rama de origen y fusionar con la rama espejo
            - name: Merge y Pull changes de forma cruzada
              run: |
                # Extraccion del nombre de la rama actual
                CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
                echo "Rama de activacion del push: $CURRENT_BRANCH"

                if [[ "$CURRENT_BRANCH" == Feature/* || "$CURRENT_BRANCH" == Feature ]]; then
                    TARGET_BRANCH="HotFix"

                    echo "Rama objetivo detectada: Sincronizacion hacia $TARGET_BRANCH"

                    git checkout -B $TARGET_BRANCH origin/$TARGET_BRANCH
                    git merge origin/$CURRENT_BRANCH --no-edit
                    git push origin $TARGET_BRANCH

                elif [[ "$CURRENT_BRANCH" == HotFix/* || "$CURRENT_BRANCH" == HotFix ]]; then
                    TARGET_BRANCH="Feature"

                    echo "Rama objetivo detectada: Sincronizacion hacia $TARGET_BRANCH"

                    git checkout -B $TARGET_BRANCH origin/$TARGET_BRANCH
                    git merge origin/$CURRENT_BRANCH --no-edit
                    git push origin $TARGET_BRANCH
                fi
