name: API Ops CD Pipeline Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./API

    steps:
      #1. Copiado del codigo del repositorio
      - name: Checkout codigo del repositorio
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            API

      #2. Configuracion de node js
      - name: Inicializado de ambiente de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "./API/package-lock.json"

      #3. Creacion de archivo .env simulado para su uso en el pipeline
      - name: Creacion archivo .env para pruebas
        run: |
          echo "PORT=3000" >> .env
          echo "JWT_SECRET=${{ secrets.TEST_JWT_SECRET }}" >> .env
          echo "DB_HOST=db-service" >> .env
          echo "DB_USER=${{ secrets.TEST_DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}" >> .env
          echo "DB_NAME=ops_dc_test" >> .env
          echo "DB_ROOT_PASSWORD=${{ secrets.TEST_DB_ROOT_PASSWORD }}" >> .env

      #4. Validacion de que la compilacion de Docker no falle
      - name: Build y validacion de stack docker compose
        run: |
          docker compose up --build -d

      #5. Espera a que la base de datos pase el Healthcheck configurado en docker-compose.yml
      - name: Espera por MariaDB a que este en estado Healthy
        run: |
          echo "Esperando a que la base de datos inicialice los esquemas"
          for i in {1..30}; do
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' mariadb_ops_local)
              echo "Estado actual de MariaDB: $STATUS (Intento $i/30)"

              if [ "$STATUS" == "healthy" ]; then
                  echo "Servidor saludable y operacional"
                  exit 0
              fi

              sleep 3
          done

          echo "ERROR: MariaDB no alcanzo un estado saludable a tiempo"
          exit 1

      #6. Auditoria de los logs para asegurar de que Express y MariaDB se levantaron correctamente
      - name: Comprobacion de logs de los contenedores
        run: |
          docker compose logs api-service
          docker compose logs db-service

      #7. Apagado y limpieza del entorno de pruebas
      - name: Destruccion de ambiente
        if: always()
        run: docker compose down -v

  deploy-to-server:
    runs-on: self-hosted
    needs: validate-and-test

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            API

      - name: Sincronizacion de archivos hacia el servidor
        run: |
          echo "Sincronizando cambios con el servidor"

          rsync -av --delete --exclude='node_modules/' --exclude='.env' --exclude='.gitignore' --exclude='.dockerignore' --exclude='Dockerfile' --exclude='docker-compose.yml' --exclude='SCHEMATICS.sql' API/ ~/api-ops-dc/

      - name: Recarga de PM2 y auditoria de modulos instalados
        run: |
          cd ~/api-ops-dc

          npm install --omit=dev

          pm2 reload api-ops-dc || pm2 restart api-ops-dc || pm2 start server.js --name "api-ops-dc"

          pm2 save

          echo "Despliegue finalizado y PM2 actualizado"